from __future__ import annotations

from collections.abc import Awaitable
from datetime import datetime
from typing import Protocol
from uuid import UUID

from english_vocab_trainer.domain.models import ReviewEvent, Settings, StudySession, Word, WordState

type MaybeAwaitable[T] = T | Awaitable[T]


class VocabularyRepository(Protocol):
    def close(self) -> None: ...
    def list_words(self, *, levels: list[int] | None = None, limit: int = 100) -> list[Word]: ...
    def due_words(self, now: datetime, limit: int) -> list[Word]: ...
    def get_word(self, word_id: str) -> Word | None: ...
    def update_transcript(self, word_id: str, transcript: str) -> Word: ...
    def state(self, word_id: str) -> WordState: ...
    def has_active_review(self, word_id: str) -> bool: ...
    def append_event(self, event: ReviewEvent, expected_version: int) -> WordState: ...
    def get_event(self, event_id: UUID) -> ReviewEvent | None: ...
    def void_event(self, event_id: UUID) -> WordState: ...
    def get_settings(self) -> Settings: ...
    def update_settings(self, daily_target: int) -> Settings: ...
    def create_session(
        self, session_id: str, kind: str, words: list[str], created_at: datetime
    ) -> StudySession: ...
    def get_session(self, session_id: str) -> StudySession | None: ...
    def progress(self, now: datetime) -> dict[str, int]: ...


class AsyncVocabularyRepository(Protocol):
    async def list_words(
        self, *, levels: list[int] | None = None, limit: int = 100
    ) -> list[Word]: ...
    async def due_words(self, now: datetime, limit: int) -> list[Word]: ...
    async def get_word(self, word_id: str) -> Word | None: ...
    async def state(self, word_id: str) -> WordState: ...
    async def progress(self, now: datetime) -> dict[str, int]: ...
    async def update_transcript(self, word_id: str, transcript: str) -> Word: ...
    async def has_active_review(self, word_id: str) -> bool: ...
    async def get_event(self, event_id: UUID) -> ReviewEvent | None: ...
    async def append_event(self, event: ReviewEvent, expected_version: int) -> WordState: ...
    async def void_event(self, event_id: UUID) -> WordState: ...
    async def get_settings(self) -> Settings: ...
    async def update_settings(self, daily_target: int) -> Settings: ...
    async def create_session(
        self, session_id: str, kind: str, words: list[str], created_at: datetime
    ) -> StudySession: ...
    async def get_session(self, session_id: str) -> StudySession | None: ...
    async def close(self) -> None: ...


type AnyVocabularyRepository = VocabularyRepository | AsyncVocabularyRepository


class RepositoryProvider(Protocol):
    def for_user(self, user_id: str) -> AnyVocabularyRepository: ...
